name: ghaselk
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  url_launcher: ^5.4.11
  flutter_bloc: ^4.0.1
  shared_preferences: ^0.5.7+3
  edge_alert: ^0.0.1
  place_picker: ^0.9.14
  # firebase_core: ^0.4.5
  date_time_format: ^1.0.0+4
  # firebase_messaging: ^6.0.16
  provider: ^4.3.2+2
  device_preview: ^0.4.5
  progress_indicators: ^0.1.5
  modal_progress_hud: ^0.1.3
  carousel_slider: ^2.2.1
  scroll_snap_list: ^0.4.1
  badges: ^1.1.1
  image_picker: ^0.6.7+4
  smooth_star_rating: ^1.1.1
  convex_bottom_bar: ^2.2.0
  google_maps_flutter: ^0.5.27
  geolocator: ^5.3.1
  dio: ^3.0.9
  md2_tab_indicator: ^1.0.2
  flutter_native_splash: ^0.1.9
  share: ^0.6.4+2
  combos: ^1.2.0
  geocoder: ^0.2.1
  timer_count_down: ^1.0.2
  great_circle_distance2: ^1.0.1+1
  location: ^2.3.5
  google_map_location_picker: ^3.3.3
  on_boarding_ui: ^0.0.4
  flutter_cupertino_date_picker: ^1.0.26+2
  grouped_buttons: ^1.0.4
  flutter_numpad_widget: ^0.1.1
  flutter_svg: ^0.18.1
  custom_navigator: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lang/
  fonts:
    - family: cairo
      fonts:
        - asset: fonts/cairo/Cairo-Black.ttf
        - asset: fonts/cairo/Cairo-Bold.ttf
        - asset: fonts/cairo/Cairo-SemiBold.ttf
    - family: GE SS Two
      fonts:
        - asset: fonts/GE/GE_SS_Two_Light.otf
          weight: 300
        - asset: fonts/GE/GE_SS_Two_Medium.otf
          weight: 400  
